name: catbreeds
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  freezed_annotation: ^0.15.0
  flutter_meedu: ^5.2.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.1
  http: ^0.13.4

flutter_native_splash:
  image: assets/images/splashl.png
  color: "#ffffff"
  image_dark: assets/images/splashd.png
  color_dark: "#000000"


dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^0.15.0+1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
